Repository notional-labs/dig-mobile-app, pull requests merged in 2022-05, with the labels that each got.

#47 Implement pull to refresh Staking screen
  lib/app/cubit/staking/staking_cubit.dart
  lib/app/cubit/staking/staking_state.dart
  lib/app/page/staking/staking_page.dart
Labels: enhancement

#48 Implement pull to refresh Proposals screen
  lib/app/cubit/proposals/proposals_cubit.dart
  lib/app/cubit/proposals/proposals_state.dart
  lib/app/page/proposals_flow/proposals/proposals_page.dart
Labels: enhancement

#51 Generate code
  dig_core/lib/src/di/di.config.dart
  lib/di/di.config.dart
Labels: bug

#52 Pass validator selected to Delegate dialog
  lib/app/cubit/staking/delegate/delegate_cubit.dart
  lib/app/cubit/staking/staking_cubit.dart
  lib/app/cubit/staking/staking_state.dart
  lib/app/page/staking/delegate/delegate_widget.dart
  lib/app/page/staking/staking_page.dart
Labels: enhancement

#54 Fix fee logic
  lib/app/cubit/active_account/transfer_token/transfer_token_cubit.dart
Labels: enhancement

#59 Fix the wrong state when switching account
  lib/app/cubit/active_account/active_account_cubit.dart
  lib/app/designsystem/custom/ds_wallet_address.dart
  lib/app/page/active_account/active_account_page.dart
Labels: bug

#60 Update the validation for the transfer token feature
  lib/app/viewmodel/transfer_token_viewmodel.dart
  lib/assets/l10n/intl_en.arb
  lib/generated/intl/messages_en.dart
  lib/generated/l10n.dart
Labels: bug, enhancement

#61 Fix bug UI create proposal button in proposals_page
  lib/app/page/proposals_flow/proposals/proposals_page.dart
Labels: bug

#65 Fix tranfer token show wrong error message
  ios/Runner/Info.plist
  lib/app/viewmodel/transfer_token_viewmodel.dart
Labels: bug
